# Minimal Go repackaging builder (debhelper only).
FROM debian:trixie-slim
RUN : \
    && apt-get update -qq \
    && DEBIAN_FRONTEND=noninteractive apt-get install \
        -qq -y --no-install-recommends \
        build-essential \
        debhelper \
        devscripts \
        equivs \
        fakeroot \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
